big move to create functions for each sub commands, more src reorg works ;)

diff --git a/bin/rocky b/bin/rocky
--- a/bin/rocky
+++ b/bin/rocky
@@ -7,7 +7,7 @@
 #       rocky   - Getting a Rocky package maintainer build development configuration setup.
 #
 # REVISION HISTORY
-#       04/01/2021    Gregory M. Kurtzer original
+#       04/01/2021    Gregory M. Kurtzer original 
 #       04/17/2021    T.J. Yang  merging rocky* commands.
 #
 # DESCRIPTION
@@ -17,7 +17,6 @@
 # RETURN CODE
 #       SUCCESS (=0) - script completed successfully
 #       ERROR   (=1) - error ... bad things happened
-#       SKIP    (=2) - startup or shutdown was skipped
 #  REFERENCE:
 #   1. https://github.com/rocky-linux/devtools
 #
@@ -33,6 +32,9 @@ PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
 SUCCESS=0
 ERROR=1
 SRPMPROC=/usr/local/bin/srpmproc
+RPMBUILD=`which rpmbuild`
+DIFF=`which diff`
+MOCK=`which mock`
 export SUCCESS ERROR SRPMPROC PATH
 
 #
@@ -43,52 +45,32 @@ export SUCCESS ERROR SRPMPROC PATH
 exit_code=${SUCCESS}
 err_msg=""
 ARCH=`uname -m`
+
 #
-# **************************** MAIN SCRIPT ************************************
+# **************************** FUNCTION   ************************************
 #
 
-# WHAT: Verify logged in as root
-# WHY:  Must be logged in as root user (in case of manual operation).
-#
-#if [ ${exit_code} -eq ${SUCCESS} ]; then
-#    x=`id | sed -e 's/uid=\([0-9][0-9]*\)\(.*\)$/\1/'`
-#    if [ ${x} -ne 0 ]; then
-#	echo "ERROR:   Must be superuser (root) to execute this script." 1>&2
-#	exit_code=${ERROR}
-#	exit ${exit_code}
-#    fi
-#fi
-#
-# WHAT: Issue error message if no script action is specified
-# WHY:  at least of  star/stop/status action is needed
-#
-
-if [ $# -eq  0  ]; then
-    echo "ERROR:  $0 {get NAME|build NAME |prep NAME |patch NAME |mkcfg NAME |help}" 1>&2
-    echo "Ex:  $0 get sed to retrieve sed srpms" 1>&2
-    exit_code=${ERROR}
+ get(){
+NAME="$2"
+if [ -z "${NAME}" ]; then
+    echo "usage: rocky get NAME"
+    echo "usage: $0 $1 $2"
     exit ${exit_code}
 fi
+if [ -d "${HOME}/rocky/patch/${NAME}.git" ]; then
+    echo "NOTICE: Will merge local configs into pulled package"
+    ( cd "${HOME}/rocky/patch/${NAME}.git"; git add .; git commit -m "update" ) ||:
+fi
+test -d "$HOME/rocky/rpms/${NAME}" && rm -rf "$HOME/rocky/rpms/${NAME}"
+test -d /tmp/srpmproc-cache || mkdir /tmp/srpmproc-cache
+mkdir -p "$HOME/rocky/rpms/${NAME}"
+${SRPMPROC} --version 8 --upstream-prefix "file://$HOME/rocky" --storage-addr file:///tmp/srpmproc-cache --source-rpm "$NAME" --tmpfs-mode "$HOME/rocky/rpms/${NAME}"
+echo "Package has been pulled to: $HOME/rocky/rpms/${NAME} by srpmproc"
+ }
 
-case $1 in
-    get)
-	NAME="$2"
-	if [ -z "${NAME}" ]; then
-	    echo "usage: rocky get NAME"
-	    exit ${exit_code}
-	fi
-	if [ -d "${HOME}/rocky/patch/${NAME}.git" ]; then
-	    echo "NOTICE: Will merge local configs into pulled package"
-	    ( cd "${HOME}/rocky/patch/${NAME}.git"; git add .; git commit -m "update" ) ||:
-	fi
-	test -d "$HOME/rocky/rpms/${NAME}" && rm -rf "$HOME/rocky/rpms/${NAME}"
-	test -d /tmp/srpmproc-cache || mkdir /tmp/srpmproc-cache
-	mkdir -p "$HOME/rocky/rpms/${NAME}"
-	${SRPMPROC} --version 8 --upstream-prefix "file://$HOME/rocky" --storage-addr file:///tmp/srpmproc-cache --source-rpm "$NAME" --tmpfs-mode "$HOME/rocky/rpms/${NAME}"
-	echo "Package has been pulled to: $HOME/rocky/rpms/${NAME} by srpmproc"
-	;;
-    build)
-	NAME="$2"
+ build()
+ {
+     	NAME="$2"
 	BRANCH="$3"
 	MODULE="$4"
 	
@@ -135,12 +117,14 @@ case $1 in
 	set -e
 	createrepo /usr/share/nginx/html/repo
 	#cd "${HOME}/rocky/rpms/${NAME}/${BRANCH}"
-	rpmbuild -bs --nodeps --define "%_topdir ${HOME}/rocky/rpms/${NAME}/${BRANCH}" --define "dist .el8" "${HOME}/rocky/rpms/${NAME}/${BRANCH}/SPECS/${NAME}.spec"
-	mock -r "$MOCKCONFIG" --resultdir="${HOME}/rocky/builds/${NAME}/${BRANCH}" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SRPMS/${NAME}*.src.rpm --isolation=simple --cleanup-after ${MOCKARGS:-}
+	${RPMBUILD} -bs --nodeps --define "%_topdir ${HOME}/rocky/rpms/${NAME}/${BRANCH}" --define "dist .el8" "${HOME}/rocky/rpms/${NAME}/${BRANCH}/SPECS/${NAME}.spec"
+	${MOCK} -r "$MOCKCONFIG" --resultdir="${HOME}/rocky/builds/${NAME}/${BRANCH}" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SRPMS/${NAME}*.src.rpm --isolation=simple --cleanup-after ${MOCKARGS:-}
 	cp ${HOME}/rocky/builds/${NAME}/${BRANCH}/*.rpm ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SRPMS/*.src.rpm /usr/share/nginx/html/repo/
 	createrepo /usr/share/nginx/html/repo
-	;;
-    prep)
+
+ }
+ prep()
+ {
 	set -e
 	NAME="$2"
 	BRANCH="$3"
@@ -178,10 +162,12 @@ case $1 in
 	    ( cd "$HOME/rocky/patch/${NAME}.git" && git init && git checkout -b main )
 	fi
 	
-	rpmbuild -bp --nodeps --define "%_topdir ${HOME}/rocky/rpms/${NAME}/${BRANCH}" --define "_builddir ${HOME}/rocky/_work/${NAME}/${BRANCH}" --define "dist .el8" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SPECS/*.spec
+	${RPMBUILD} -bp --nodeps --define "%_topdir ${HOME}/rocky/rpms/${NAME}/${BRANCH}" --define "_builddir ${HOME}/rocky/_work/${NAME}/${BRANCH}" --define "dist .el8" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SPECS/*.spec
 	echo "Created ${HOME}/rocky/_work/${NAME}/${BRANCH}/"
-	;;
-    patch)
+     
+ }
+ patch()
+ {
 	set -e
 	NAME=`pwd | sed -e "s@^$HOME/rocky/_work/@@" | awk -F '/' '{print $1}'`
 	BRANCH=`pwd | sed -e "s@^$HOME/rocky/_work/@@" | awk -F '/' '{print $2}'`
@@ -218,7 +204,7 @@ case $1 in
 	    ( cd "$HOME/rocky/patch/${NAME}.git" && git init && git checkout -b main )
 	fi
 	
-	rpmbuild -bp --nodeps --define "%_topdir ${HOME}/rocky/rpms/${NAME}/${BRANCH}" --define "_builddir ${HOME}/rocky/_work/${NAME}/${BRANCH}/.patchdir" --define "dist .el8" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SPECS/*.spec
+	${RPMBUILD} -bp --nodeps --define "%_topdir ${HOME}/rocky/rpms/${NAME}/${BRANCH}" --define "_builddir ${HOME}/rocky/_work/${NAME}/${BRANCH}/.patchdir" --define "dist .el8" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SPECS/*.spec
 	
 	cd "${HOME}/rocky/_work/${NAME}/${BRANCH}/.patchdir"
 	
@@ -227,9 +213,9 @@ case $1 in
 	
 	set +e
 	
-	diff -ru a b > "$HOME/rocky/patch/${NAME}.git/ROCKY/_supporting/$PATCHNAME"
+	${DIFF} -ru a b > "$HOME/rocky/patch/${NAME}.git/ROCKY/_supporting/$PATCHNAME"
 	if [ $? -gt "1" ]; then
-	    echo "ERROR: Diff failed"
+	    echo "ERROR: ${DIFF} failed"
 	    exit 255
 	fi
 	
@@ -257,8 +243,10 @@ EOF
 	
 	echo "Regetting '${NAME}' to integrate patch..."
 	rocky get ${NAME}
-	;;
-    mkcfg)
+     
+ }
+ mkcfg()
+ {
 	NAME="$2"
 	
 	if [ -z "$NAME" ]; then
@@ -288,6 +276,51 @@ EOF
 	if [ -d "${HOME}/rocky/rpms/${NAME}" ]; then
 	    echo "WARNING: You will have to rerun 'rockyget ${NAME}' to test"
 	fi
+     
+ }
+
+#
+# **************************** MAIN SCRIPT ************************************
+#
+
+# WHAT: Verify running  as root
+# WHY:  Must be logged in as root user (in case of manual operation).
+#
+#if [ ${exit_code} -eq ${SUCCESS} ]; then
+#    x=`id | sed -e 's/uid=\([0-9][0-9]*\)\(.*\)$/\1/'`
+#    if [ ${x} -ne 0 ]; then
+#	echo "ERROR:   Must be superuser (root) to execute this script." 1>&2
+#	exit_code=${ERROR}
+#	exit ${exit_code}
+#    fi
+#fi
+#
+# WHAT: Issue error message if no script action is specified
+# WHY:  at least of  star/stop/status action is needed
+#
+
+if [ $# -eq  0  ]; then
+    echo "ERROR:  $0 {get NAME|build NAME |prep NAME |patch NAME |mkcfg NAME |help}" 1>&2
+    echo "Ex:  $0 get sed to retrieve sed SRPM" 1>&2
+    exit_code=${ERROR}
+    exit ${exit_code}
+fi
+
+case $1 in
+    get)
+	get $1 $2
+	;;
+    build)
+        build $1 $2 $3 $4
+	;;
+    prep)
+        prep $1 $2 $3
+	;;
+    patch)
+	patch $1 $2
+	;;
+    mkcfg)
+	mkcfg $1 $2
 	;;
     help)
 	echo "$0 get   sed : get sed srpm locally via srpmproc."
