Updates with automatic builds for modularity

diff --git a/bin/rockybuild b/bin/rockybuild
--- a/bin/rockybuild
+++ b/bin/rockybuild
@@ -1,9 +1,10 @@
 #!/bin/sh
 
-ARCH=`uname -m`
 NAME="$1"
 BRANCH="$2"
 MODULE="$3"
+ARCH=`uname -m`
+MOCKCFG="/etc/mock/rocky-$ARCH.cfg"
 
 if [ -z "$NAME" ]; then
     echo "USAGE: $0 [PACKAGE NAME] [BRANCH]"
@@ -12,52 +13,72 @@ else
     shift
 fi
 
-if [ -z "$BRANCH" ]; then
-    BRANCH="r8"
-else
-    shift
-fi
 
-
-if [ -z "$MODULE" ]; then
-    MOCKCONFIG="/etc/mock/rocky.$ARCH/baseos.cfg"
-else
-    if [ -f "/etc/mock/rocky.$ARCH/modules/$MODULE.cfg" ]; then
-        MOCKCONFIG="/etc/mock/rocky.$ARCH/modules/$MODULE.cfg"
-        shift
-    else
-        echo "ERROR: Could not find module config for: '$MODULE'"
-        exit 255
-    fi
-fi
-
+# SANITY
 if [ ! -d "${HOME}/rocky/rpms/${NAME}" ]; then
-    echo "Importing package: ${NAME}"
-    if ! rockyget "${NAME}"; then
-        echo "Failed to import package: ${NAME}"
-        exit 255
+    echo "ERROR: package name is not imported"
+    exit 1
+fi
+if [ -z "$BRANCH" ]; then
+    BRANCHES=`ls -1 ${HOME}/rocky/rpms/${NAME} | wc -l`
+    if [ "$BRANCHES" -eq 1 ]; then
+        BRANCH=`( cd ${HOME}/rocky/rpms/${NAME}/ ; ls -d *)`
+    else
+        echo "ERROR: What branch do you want to build:"
+        ( cd $HOME/rocky/rpms/${NAME}; ls -1 )
+        exit 1
     fi
 fi
-
 if [ ! -d "${HOME}/rocky/rpms/${NAME}/${BRANCH}" ]; then
     echo "This package branch does not exist."
     exit 255
 fi
-    
+
+
+# MODULARITY
+TMPCFG=`mktemp /tmp/rockybuild-mock-XXXXXXX.cfg`
+cat "$MOCKCFG" > "$TMPCFG"
+
+if [ -n "$MODULE" ]; then
+    if [ -f "/etc/rocky/devtools/modulefiles/$MODULE" ]; then
+        echo "Found module configuration for: $MODULE"
+        rockymockgen < "/etc/rocky/devtools/modulefiles/$MODULE" >> "$TMPCFG"
+    else
+        echo "WARNING: Could not find module config for: $MODULE"
+        sleep 5
+    fi
+fi
+
+
+STREAM=`echo $BRANCH | sed -e 's/r8-stream-//'`
+grep "^$NAME " /etc/rocky/devtools/modulelist | while read name module stream; do
+    if [ "$STREAM" == "$stream" ]; then
+        if [ -f "/etc/rocky/devtools/modulefiles/$module:$stream" ]; then
+            echo "Found module configuration for: $module:$stream"
+            rockymockgen < "/etc/rocky/devtools/modulefiles/$module:$stream" >> "$TMPCFG"
+        else
+            echo "WARNING: Could not find module config for: $module:$stream"
+            sleep 5
+        fi
+    fi
+done
+
+echo "MOCKCFG=$TMPCFG"
+
 test -d "${HOME}/rocky/builds/${NAME}/${BRANCH}" || mkdir -p "${HOME}/rocky/builds/${NAME}/${BRANCH}"
 
 set -e
 
 createrepo /usr/share/nginx/html/repo
 
-
-#cd "${HOME}/rocky/rpms/${NAME}/${BRANCH}"
-
 rpmbuild -bs --nodeps --define "%_topdir ${HOME}/rocky/rpms/${NAME}/${BRANCH}" --define "dist .el8" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SPECS/*.spec
 
-mock -r "$MOCKCONFIG" --resultdir="${HOME}/rocky/builds/${NAME}/${BRANCH}" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SRPMS/*.src.rpm --isolation=simple --cleanup-after ${MOCKARGS:-}
+mock -r "$TMPCFG" --resultdir="${HOME}/rocky/builds/${NAME}/${BRANCH}" ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SRPMS/*.src.rpm --isolation=simple --cleanup-after ${MOCKARGS:-}
 
 cp ${HOME}/rocky/builds/${NAME}/${BRANCH}/*.rpm ${HOME}/rocky/rpms/${NAME}/${BRANCH}/SRPMS/*.src.rpm /usr/share/nginx/html/repo/
 
 createrepo /usr/share/nginx/html/repo
 
+if [ -n "$TMPCFG" ]; then
+    rm "$TMPCFG"
+fi
